apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - image: {image}
        name: {name}
        ports:
        - containerPort: 9200
          name: http
        volumemounts:
        - name: {name}
          mountPath: /etc/elasticsearch
      volumes:
      - name: {name}-hostpath
        hostPath:
          path: {hostpath}
          type: DirectoryOrCreate
      - name: {name}
        configMap: 
          name: {name}-config