apiVersion: v1
kind: Service
metadata:
  name: {name}-service
  labels:
    app: {name}
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
    protocol: https
  selector:
    app: {name}
  type: ClusterIP